POST http://localhost:3002/api/persons
Content-Type: application/json

{
    "name": "Lorenzo",
    "number": "035555555557"
}

###

GET http://localhost:3002/api/persons

###
DELETE  http://localhost:3002/api/persons/67056eb61e7cb36ac5a79efc

###

GET http://localhost:3002/api/persons/67068d5888d2b39e1d40c28b